// <auto-generated />
using System;
using HNSHOP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HNSHOP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250226124216_Add_IsVerified_To_Account")]
    partial class Add_IsVerified_To_Account
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HNSHOP.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifyToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "avatar1.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            IsVerified = false,
                            Password = "$2a$11$KtqLMFb.sMl1YK/dM1bKDOD3s3ih4I8irHqkkB6bPQVW0.9S090dG",
                            Phone = "0912345678",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VerifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VerifyToken = "token123"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "avatar2.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user1@example.com",
                            IsVerified = false,
                            Password = "$2a$11$F9fDbvpV3UUnHxXUllLp7uZpdVClZQiP1Ke7H9b/a8ML2nRgrecq6",
                            Phone = "0934567890",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VerifyToken = "token456"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "avatar3.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user2@example.com",
                            IsVerified = false,
                            Password = "$2a$11$5GqnosrWGf4NgpXdVsgl7usWkDNmxawnueq/heqs5.Fq0.nOUoS0m",
                            Phone = "0987654321",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VerifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VerifyToken = "token789"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "avatar4.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "seller1@example.com",
                            IsVerified = false,
                            Password = "$2a$11$e.NzQLJCtqm40pgZVQJR8OsREFpRqvCHCfUlvgTSzePYA5B3VePwm",
                            Phone = "0901234567",
                            RoleId = 3,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VerifyToken = "token101"
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "avatar5.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "seller2@example.com",
                            IsVerified = false,
                            Password = "$2a$11$PgCCN3J2dsV6zgwBOAlsFetyV0iHLPNlHY3wwfjViH0uR/o3dwvPO",
                            Phone = "0912345678",
                            RoleId = 3,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VerifiedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VerifyToken = "token202"
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressDetail = "123 Đường Lê Lợi, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh",
                            CustomerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddressDetail = "45 Ngõ 19, Phường Hàng Bài, Quận Hoàn Kiếm, Hà Nội",
                            CustomerId = 1
                        },
                        new
                        {
                            Id = 3,
                            AddressDetail = "678 Đường Trần Hưng Đạo, Phường Tân Bình, Quận Tân Phú, TP. Hồ Chí Minh",
                            CustomerId = 2
                        },
                        new
                        {
                            Id = 4,
                            AddressDetail = "32 Đường Nguyễn Thị Minh Khai, Phường 6, Quận 3, TP. Hồ Chí Minh",
                            CustomerId = 2
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("CustomerTypeId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 2,
                            CustomerTypeId = 1,
                            Description = "Mô tả của khách hàng Nguyễn Văn A",
                            Dob = new DateOnly(1990, 5, 10),
                            Name = "Nguyễn Văn A"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 3,
                            CustomerTypeId = 2,
                            Description = "Khách hàng mới",
                            Dob = new DateOnly(1985, 3, 15),
                            Name = "Trần Thị B"
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.CustomerNotification", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.HasKey("CustomerId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("CustomerNotifications");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            NotificationId = 1,
                            IsRead = false
                        },
                        new
                        {
                            CustomerId = 1,
                            NotificationId = 2,
                            IsRead = false
                        },
                        new
                        {
                            CustomerId = 2,
                            NotificationId = 3,
                            IsRead = false
                        },
                        new
                        {
                            CustomerId = 2,
                            NotificationId = 4,
                            IsRead = false
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.CustomerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Toàn bộ khách hàng thông thường có mua hàng nhưng ít",
                            Name = "Khách hàng thông thường"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Toàn bộ khách hàng thân thiết, thường xuyên mua hàng",
                            Name = "Khách hàng thân thiết"
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.CustomerTypeSaleEvent", b =>
                {
                    b.Property<int>("CustomerTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SaleEventId")
                        .HasColumnType("int");

                    b.HasKey("CustomerTypeId", "SaleEventId");

                    b.HasIndex("SaleEventId");

                    b.ToTable("CustomerTypeSaleEvents");

                    b.HasData(
                        new
                        {
                            CustomerTypeId = 1,
                            SaleEventId = 1
                        },
                        new
                        {
                            CustomerTypeId = 1,
                            SaleEventId = 2
                        },
                        new
                        {
                            CustomerTypeId = 2,
                            SaleEventId = 3
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.DetailOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(9, 1)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("DetailOrders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 799.9m
                        },
                        new
                        {
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 1499.0m
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 3,
                            UnitPrice = 249.5m
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 249.5m
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 59.9m
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 6,
                            Quantity = 6,
                            UnitPrice = 89.0m
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.Like", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            ProductId = 1,
                            CreatedAt = new DateTime(2023, 12, 31, 23, 55, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CustomerId = 1,
                            ProductId = 2,
                            CreatedAt = new DateTime(2023, 12, 31, 23, 57, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CustomerId = 2,
                            ProductId = 5,
                            CreatedAt = new DateTime(2023, 12, 31, 23, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CustomerId = 1,
                            ProductId = 8,
                            CreatedAt = new DateTime(2023, 12, 31, 23, 48, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Hãy kiểm tra tài khoản của bạn để biết thêm thông tin.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = false,
                            Title = "Thông báo quan trọng"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Hệ thống sẽ bảo trì từ 2 AM đến 4 AM ngày mai.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = false,
                            Title = "Cập nhật hệ thống"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Nhận ngay 20% giảm giá cho đơn hàng đầu tiên của bạn!",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            Title = "Tin khuyến mãi"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Bạn có một hóa đơn chưa thanh toán. Vui lòng thanh toán ngay.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = false,
                            Title = "Nhắc nhở thanh toán"
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(9, 1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            PaymentStatus = "Pending",
                            Status = "Processing",
                            Total = 250m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            PaymentStatus = "Completed",
                            Status = "Shipping",
                            Total = 120m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            PaymentStatus = "Completed",
                            Status = "Delivered",
                            Total = 75.9m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            PaymentStatus = "Pending",
                            Status = "Cancelled",
                            Total = 450.75m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9, 1)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("ShopId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Điện thoại thông minh với màn hình AMOLED và camera 108MP.",
                            Name = "Điện thoại thông minh Galaxy X12",
                            Price = 799.9m,
                            ProductTypeId = 3,
                            Quantity = 50,
                            ShopId = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Laptop cao cấp với màn hình 15 inch 4K và hiệu năng mạnh mẽ.",
                            Name = "Laptop Dell XPS 15",
                            Price = 1499.0m,
                            ProductTypeId = 3,
                            Quantity = 30,
                            ShopId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tai nghe không dây với công nghệ chống ồn và âm thanh chất lượng cao.",
                            Name = "Tai nghe Bluetooth AirPods Pro",
                            Price = 249.5m,
                            ProductTypeId = 3,
                            Quantity = 100,
                            ShopId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Máy ảnh mirrorless với cảm biến full-frame và khả năng quay video 8K.",
                            Name = "Máy ảnh Canon EOS R5",
                            Price = 3899.0m,
                            ProductTypeId = 3,
                            Quantity = 15,
                            ShopId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Áo sơ mi nam chất liệu cotton cao cấp, kiểu dáng cổ điển.",
                            Name = "Áo sơ mi nam Oxford",
                            Price = 59.9m,
                            ProductTypeId = 4,
                            Quantity = 200,
                            ShopId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Váy đầm dành cho văn phòng với thiết kế tinh tế và thanh lịch.",
                            Name = "Váy đầm công sở thanh lịch",
                            Price = 89.0m,
                            ProductTypeId = 4,
                            Quantity = 150,
                            ShopId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Giày thể thao cao cấp với đệm khí Boost, phù hợp cho vận động.",
                            Name = "Giày thể thao Adidas UltraBoost",
                            Price = 129.0m,
                            ProductTypeId = 4,
                            Quantity = 80,
                            ShopId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Áo khoác giữ ấm với lông cừu mềm mại và kiểu dáng thời trang.",
                            Name = "Áo khoác lông cừu nữ",
                            Price = 150.0m,
                            ProductTypeId = 4,
                            Quantity = 60,
                            ShopId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Máy lọc không khí hiệu suất cao với bộ lọc HEPA giúp không khí trong lành.",
                            Name = "Máy lọc không khí Philips",
                            Price = 199.9m,
                            ProductTypeId = 2,
                            Quantity = 70,
                            ShopId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Tủ lạnh tiết kiệm năng lượng với dung tích 400L và công nghệ Inverter.",
                            Name = "Tủ lạnh LG Inverter 400L",
                            Price = 899.0m,
                            ProductTypeId = 2,
                            Quantity = 25,
                            ShopId = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Lò vi sóng với nhiều chế độ nấu và công suất mạnh mẽ.",
                            Name = "Lò vi sóng Panasonic",
                            Price = 79.9m,
                            ProductTypeId = 2,
                            Quantity = 90,
                            ShopId = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Máy giặt cửa trên với công nghệ giặt sạch hiệu quả và dung tích 7kg.",
                            Name = "Máy giặt Samsung 7kg",
                            Price = 399.0m,
                            ProductTypeId = 2,
                            Quantity = 40,
                            ShopId = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Kem dưỡng da ban đêm giúp cấp ẩm và làm sáng da.",
                            Name = "Kem dưỡng da Laneige",
                            Price = 65.0m,
                            ProductTypeId = 1,
                            Quantity = 100,
                            ShopId = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Son môi với chất lượng cao, màu sắc bền và không khô môi.",
                            Name = "Son môi MAC Matte",
                            Price = 25.0m,
                            ProductTypeId = 1,
                            Quantity = 200,
                            ShopId = 1
                        },
                        new
                        {
                            Id = 15,
                            Description = "Sữa rửa mặt chiết xuất trà xanh giúp làm sạch da và giảm mụn.",
                            Name = "Sữa rửa mặt Innisfree",
                            Price = 18.0m,
                            ProductTypeId = 1,
                            Quantity = 150,
                            ShopId = 1
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Path = "product1_image1.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Path = "product1_image2.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            Path = "product2_image1.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            Path = "product2_image2.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            Path = "product3_image1.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 6,
                            Path = "product3_image2.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 7,
                            Path = "product4_image1.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 8,
                            Path = "product4_image2.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 9,
                            Path = "product5_image1.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 10,
                            Path = "product5_image2.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 11,
                            Path = "product6_image1.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 12,
                            Path = "product6_image2.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 13,
                            Path = "product7_image1.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 14,
                            Path = "product7_image2.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 15,
                            Path = "product8_image1.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 16,
                            Path = "product8_image2.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 17,
                            Path = "product9_image1.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 18,
                            Path = "product9_image2.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 19,
                            Path = "product10_image1.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 20,
                            Path = "product10_image2.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 21,
                            Path = "product11_image1.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 22,
                            Path = "product11_image2.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 23,
                            Path = "product12_image1.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 24,
                            Path = "product12_image2.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 25,
                            Path = "product13_image1.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 26,
                            Path = "product13_image2.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 27,
                            Path = "product14_image1.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 28,
                            Path = "product14_image2.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 29,
                            Path = "product15_image1.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 30,
                            Path = "product15_image2.jpg",
                            ProductId = 15
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.ProductSaleEvent", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SaleEventId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "SaleEventId");

                    b.HasIndex("SaleEventId");

                    b.ToTable("ProductSaleEvents");

                    b.HasData(
                        new
                        {
                            ProductId = 5,
                            SaleEventId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            SaleEventId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            SaleEventId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            SaleEventId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            SaleEventId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            SaleEventId = 1
                        },
                        new
                        {
                            ProductId = 11,
                            SaleEventId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            SaleEventId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            SaleEventId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            SaleEventId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            SaleEventId = 2
                        },
                        new
                        {
                            ProductId = 13,
                            SaleEventId = 3
                        },
                        new
                        {
                            ProductId = 14,
                            SaleEventId = 3
                        },
                        new
                        {
                            ProductId = 15,
                            SaleEventId = 3
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mỹ phẩm là các sản phẩm chăm sóc cá nhân được thiết kế để làm đẹp, bảo vệ hoặc cải thiện vẻ ngoài của da, tóc, móng và cơ thể. Chúng bao gồm nhiều loại sản phẩm như kem dưỡng da, son môi, phấn nền, mascara, dầu gội, và nước hoa. Mỹ phẩm có thể chứa các thành phần tự nhiên hoặc tổng hợp, giúp làm sạch, dưỡng ẩm, chống lão hóa, và bảo vệ da khỏi các tác động xấu từ môi trường.",
                            Name = "Mỹ phẩm"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sản phẩm gia dụng là các vật dụng được sử dụng hàng ngày trong gia đình, phục vụ cho các nhu cầu cơ bản như nấu nướng, vệ sinh, giặt giũ và trang trí. Chúng bao gồm nhiều loại như đồ điện gia dụng (máy giặt, tủ lạnh, lò vi sóng), đồ dùng nhà bếp (nồi, chảo, bát đĩa), thiết bị vệ sinh (máy hút bụi, cây lau nhà), và các sản phẩm trang trí nội thất. Sản phẩm gia dụng giúp tối ưu hóa công việc trong nhà, mang lại sự tiện nghi và thoải mái cho người dùng.",
                            Name = "Gia dụng"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sản phẩm điện tử là các thiết bị sử dụng công nghệ điện để hoạt động, đáp ứng nhu cầu giải trí, liên lạc, làm việc và học tập. Chúng bao gồm điện thoại di động, máy tính xách tay, máy tính bảng, tivi, tai nghe và các thiết bị gia dụng thông minh. Sản phẩm điện tử thường được trang bị các tính năng tiên tiến như kết nối internet, màn hình cảm ứng, và công nghệ không dây, giúp người dùng dễ dàng tương tác và cải thiện hiệu suất trong cuộc sống hàng ngày.",
                            Name = "Điện tử"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sản phẩm thời trang bao gồm quần áo, giày dép, phụ kiện như túi xách, mũ, và trang sức, được thiết kế để thể hiện phong cách cá nhân và xu hướng thẩm mỹ. Chúng không chỉ đáp ứng nhu cầu mặc hàng ngày mà còn phản ánh cá tính, văn hóa, và thời đại. Các sản phẩm thời trang đa dạng từ trang phục công sở, dạo phố, đến trang phục dạ tiệc, thường được cập nhật liên tục theo mùa và xu hướng thời trang thế giới.",
                            Name = "Thời trang"
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RatingValue")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Sản phẩm chất lượng tốt, đáng giá tiền.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            OrderId = 1,
                            ProductId = 1,
                            RatingValue = 5,
                            UserName = "Nguyễn Văn A"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Sản phẩm không như mong đợi, cần cải thiện.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            OrderId = 1,
                            ProductId = 2,
                            RatingValue = 4,
                            UserName = "Nguyễn Văn A"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Dịch vụ tuyệt vời, sản phẩm hoàn hảo.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            OrderId = 1,
                            ProductId = 3,
                            RatingValue = 3,
                            UserName = "Nguyễn Văn A"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Tốt nhưng cần cải thiện đóng gói.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            OrderId = 2,
                            ProductId = 3,
                            RatingValue = 4,
                            UserName = "Trần Thị B"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Sản phẩm bị lỗi, không hài lòng.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            OrderId = 2,
                            ProductId = 5,
                            RatingValue = 5,
                            UserName = "Trần Thị B"
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Rất hài lòng với chất lượng và dịch vụ.",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            OrderId = 2,
                            ProductId = 6,
                            RatingValue = 2,
                            UserName = "Trần Thị B"
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shop"
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.SaleEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Illustration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SaleEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Giảm giá 20% cho tất cả các sản phẩm thời trang trong mùa hè này.",
                            Discount = 0.2f,
                            EndDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Illustration = "image1.jpg",
                            Name = "Khuyến Mãi Mùa Hè",
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giảm giá 15% cho các sản phẩm điện tử và công nghệ.",
                            Discount = 0.15f,
                            EndDate = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Illustration = "image2.jpg",
                            Name = "Ngày Hội Công Nghệ",
                            StartDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Giảm giá lên đến 30% cho tất cả các sản phẩm gia dụng và mỹ phẩm.",
                            Discount = 0.3f,
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Illustration = "image3.jpg",
                            Name = "Khuyến Mãi Cuối Năm",
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 4,
                            Description = "\"Elegance Boutique\" là điểm đến lý tưởng cho những tín đồ yêu thích thời trang và mỹ phẩm chất lượng cao. Với sứ mệnh mang đến sự hoàn hảo trong từng sản phẩm, cửa hàng của chúng tôi chuyên cung cấp các mặt hàng thời trang và mỹ phẩm từ những thương hiệu danh tiếng, nổi bật với thiết kế tinh tế và phong cách hiện đại.\n\nTại \"Elegance Boutique\", bạn sẽ tìm thấy những bộ sưu tập thời trang đa dạng, từ các trang phục công sở thanh lịch, váy đầm quyến rũ đến những bộ đồ thể thao năng động, đáp ứng mọi nhu cầu và gu thẩm mỹ của khách hàng. Chúng tôi cam kết mang đến những sản phẩm thời trang được chọn lọc kỹ lưỡng từ các thương hiệu hàng đầu, với chất lượng vải tốt nhất và kiểu dáng thời thượng.\n\nBên cạnh thời trang, cửa hàng của chúng tôi còn nổi bật với bộ sưu tập mỹ phẩm cao cấp. Chúng tôi cung cấp các sản phẩm làm đẹp từ các thương hiệu nổi tiếng, bao gồm kem dưỡng da, son môi, sữa rửa mặt và nhiều sản phẩm chăm sóc sắc đẹp khác. Các sản phẩm mỹ phẩm tại \"Elegance Boutique\" được chọn lựa với tiêu chí an toàn, hiệu quả và phù hợp với mọi loại da, giúp bạn luôn tự tin và rạng rỡ.\n\nChúng tôi hiểu rằng việc mua sắm trực tuyến có thể là một trải nghiệm thú vị và thuận tiện, vì vậy cửa hàng của chúng tôi đã đầu tư vào nền tảng thương mại điện tử hiện đại. Bạn có thể dễ dàng duyệt qua các sản phẩm, thực hiện đơn hàng và nhận hàng ngay tại nhà với dịch vụ giao hàng nhanh chóng và bảo đảm. Hãy ghé thăm \"Elegance Boutique\" và khám phá thế giới thời trang và làm đẹp đỉnh cao ngay hôm nay!",
                            Name = "Elegance Boutique"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 5,
                            Description = "\"Tech & Home Center\" là cửa hàng trực tuyến hàng đầu cung cấp các sản phẩm gia dụng và điện tử, được thiết kế để nâng cao chất lượng cuộc sống và đáp ứng nhu cầu công nghệ hiện đại của bạn. Chúng tôi tự hào mang đến cho khách hàng một trải nghiệm mua sắm tiện lợi và đa dạng với các sản phẩm chất lượng cao từ những thương hiệu uy tín.\n\nTại \"Tech & Home Center\", bạn sẽ tìm thấy một loạt các sản phẩm gia dụng thiết yếu cho ngôi nhà của bạn. Từ các thiết bị nhà bếp như máy xay sinh tố, nồi chiên không dầu, đến các thiết bị bảo trì và vệ sinh như máy hút bụi và máy lọc không khí, chúng tôi cung cấp những sản phẩm giúp bạn duy trì một môi trường sống sạch sẽ và tiện nghi.\n\nBên cạnh đó, chúng tôi còn cung cấp các thiết bị điện tử tiên tiến, bao gồm máy tính, điện thoại thông minh, TV và các phụ kiện công nghệ khác. Các sản phẩm điện tử của chúng tôi được chọn lựa từ các thương hiệu hàng đầu, đảm bảo hiệu suất vượt trội và tính năng hiện đại, đáp ứng nhu cầu giải trí, làm việc và kết nối của bạn.\n\n\"Tech & Home Center\" cam kết mang đến cho khách hàng một trải nghiệm mua sắm trực tuyến dễ dàng và thuận tiện. Với nền tảng thương mại điện tử tiên tiến, bạn có thể dễ dàng duyệt qua các sản phẩm, so sánh giá cả và đặt hàng chỉ với vài cú click chuột. Chúng tôi cung cấp dịch vụ giao hàng nhanh chóng và đáng tin cậy, cùng với chính sách đổi trả linh hoạt để đảm bảo sự hài lòng tuyệt đối của bạn.\n\nKhám phá \"Tech & Home Center\" ngay hôm nay để tìm kiếm những sản phẩm gia dụng và điện tử chất lượng cao, mang lại sự tiện lợi và hiệu suất tối ưu cho cuộc sống hàng ngày của bạn!",
                            Name = "Tech & Home Center"
                        });
                });

            modelBuilder.Entity("HNSHOP.Models.Account", b =>
                {
                    b.HasOne("HNSHOP.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HNSHOP.Models.Address", b =>
                {
                    b.HasOne("HNSHOP.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HNSHOP.Models.Customer", b =>
                {
                    b.HasOne("HNSHOP.Models.Account", "Account")
                        .WithOne("Customer")
                        .HasForeignKey("HNSHOP.Models.Customer", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HNSHOP.Models.CustomerType", "CustomerType")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("CustomerType");
                });

            modelBuilder.Entity("HNSHOP.Models.CustomerNotification", b =>
                {
                    b.HasOne("HNSHOP.Models.Customer", "Customer")
                        .WithMany("CustomerNotifications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HNSHOP.Models.Notification", "Notification")
                        .WithMany("CustomerNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("HNSHOP.Models.CustomerTypeSaleEvent", b =>
                {
                    b.HasOne("HNSHOP.Models.CustomerType", null)
                        .WithMany("CustomerTypeSaleEvents")
                        .HasForeignKey("CustomerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HNSHOP.Models.SaleEvent", null)
                        .WithMany("CustomerTypeSaleEvents")
                        .HasForeignKey("SaleEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HNSHOP.Models.DetailOrder", b =>
                {
                    b.HasOne("HNSHOP.Models.Order", "Order")
                        .WithMany("DetailOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HNSHOP.Models.Product", "Product")
                        .WithMany("DetailOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HNSHOP.Models.Like", b =>
                {
                    b.HasOne("HNSHOP.Models.Customer", "Customer")
                        .WithMany("Likes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HNSHOP.Models.Product", "Product")
                        .WithMany("Likes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HNSHOP.Models.Order", b =>
                {
                    b.HasOne("HNSHOP.Models.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HNSHOP.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HNSHOP.Models.Product", b =>
                {
                    b.HasOne("HNSHOP.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HNSHOP.Models.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("HNSHOP.Models.ProductImage", b =>
                {
                    b.HasOne("HNSHOP.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HNSHOP.Models.ProductSaleEvent", b =>
                {
                    b.HasOne("HNSHOP.Models.Product", null)
                        .WithMany("ProductSaleEvents")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HNSHOP.Models.SaleEvent", null)
                        .WithMany("ProductSaleEvents")
                        .HasForeignKey("SaleEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HNSHOP.Models.Rating", b =>
                {
                    b.HasOne("HNSHOP.Models.Customer", "Customer")
                        .WithMany("Ratings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HNSHOP.Models.Order", null)
                        .WithMany("Ratings")
                        .HasForeignKey("OrderId");

                    b.HasOne("HNSHOP.Models.Product", "Product")
                        .WithMany("Ratings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HNSHOP.Models.Shop", b =>
                {
                    b.HasOne("HNSHOP.Models.Account", "Account")
                        .WithOne("Shop")
                        .HasForeignKey("HNSHOP.Models.Shop", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("HNSHOP.Models.Account", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("HNSHOP.Models.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HNSHOP.Models.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CustomerNotifications");

                    b.Navigation("Likes");

                    b.Navigation("Orders");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("HNSHOP.Models.CustomerType", b =>
                {
                    b.Navigation("CustomerTypeSaleEvents");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("HNSHOP.Models.Notification", b =>
                {
                    b.Navigation("CustomerNotifications");
                });

            modelBuilder.Entity("HNSHOP.Models.Order", b =>
                {
                    b.Navigation("DetailOrders");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("HNSHOP.Models.Product", b =>
                {
                    b.Navigation("DetailOrders");

                    b.Navigation("Likes");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductSaleEvents");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("HNSHOP.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HNSHOP.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("HNSHOP.Models.SaleEvent", b =>
                {
                    b.Navigation("CustomerTypeSaleEvents");

                    b.Navigation("ProductSaleEvents");
                });

            modelBuilder.Entity("HNSHOP.Models.Shop", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
